#Alacritty configuration
#import = ["~/.config/alacritty/themes/catppuccin-mocha.toml"]

[shell]
program = "/usr/bin/bash"

[scrolling]
history = 100000

[window]
padding = { x = 0, y = 0 }
dynamic_padding = true
startup_mode = "Maximized"
decorations = "None"

[colors.cursor]
text = "CellBackground"
cursor = "CellForeground"

[cursor]
blink_timeout = 0
blink_interval = 600

[cursor.style]
blinking = "Always"

[font]
size = 16

[font.normal]
family = "JuliaMono"
style = "Light"

[font.bold]
family = "JuliaMono"
style = "ExtraBold"

[font.bold_italic]
family = "JuliaMono"
style = "ExtraBold Italic"

[font.italic]
family = "JuliaMono"
style = "Light Italic"

[mouse]
hide_when_typing = true
